### ISSUE TITLE
Check download URL

### ISSUE THREAD

**Issue by KimYangOfCat** [c422/c422-src#19]
@DragonJiao Hi, last night,I tried to download your PPT on May 25th, but I found the download URL is wrong.Can you check it again?

**Comment by YiqinZhao** [comment]
Please use this URL: https://cdn.coden.hk/c422/weekly-keynote/2019-05-25-jiaojinlong/%E5%AD%A6%E4%B9%A0%E5%88%86%E4%BA%AB.pptx

**Comment by seiuryuu** [comment]
Fixed.
