### ISSUE TITLE
Notice: Dependency Update

### ISSUE THREAD

**Issue by YiqinZhao** [c422/c422-src#20]
The `academic` theme had been updated to new version, a break change was introduced. The `content/en/author` needs to be renamed to `content/en/authors`. Also, same as Chinese content.

Please update your forked repo, and check if the `author` folder has been renamed correctly. 

Please give feedback about this dependency update at this issues. If you are succeed or encountered some error, let me know.

**Comment by YiqinZhao** [comment]
You may follow the following steps:

1. Update your forked repo with reverse PR or something else.
1. Do `git pull` on your **local master** branch, you may see some update
1. Checkout to your local working branch, then do `git merge master` to keep your working branch update to date.
1. Do `git submodule update` to update theme repo
1. If you still have `author` folder in `content/en` or `content/zh`, it should an empty one, just delete it. It will cause no change to your local git workspace.
1. `git push`

Above steps will help you update your working branch, please make sure update your working branch like the above every time before a new PR in the future.

**Comment by YiqinZhao** [comment]
Remember to give me feedback if you have succeeded.

**Comment by KimYangOfCat** [comment]
@YiqinZhao `git submodule update`,maybe submodule should be update?

**Comment by YiqinZhao** [comment]
> @YiqinZhao `git submodule update`,maybe submodule should be update?

Yes, a `submodule update` is optional. It is only required when `academic` theme had been updated. I will notice you first if the theme needed to be updated in the future.

**Comment by cnlisen** [comment]
👌

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
