### ISSUE TITLE
Content for Prof. Zhao, Chuan

### ISSUE THREAD

**Issue by YiqinZhao** [c422/c422-src#21]
Please add content for Prof. Zhao, Chuan who is one of our advising professor. The content should include his personal info in `author` folder and competition and award information in each post. You may want to give him a look before submit a PR. Thanks.

**Comment by KimYangOfCat** [comment]
OK,I will finish  it.

**Comment by YiqinZhao** [comment]
How is this thing going? Should we close this issue?

**Comment by KimYangOfCat** [comment]
hum~During those days，I didn't  push it. I will ask him tomorrow. Please  wait one more day！

**Comment by YiqinZhao** [comment]
No hurry. Just wondering about how is it going on. If Prof. Zhao has no initiative in this thing, we should just leave him that way.

**Comment by KimYangOfCat** [comment]
Sorry，the thing failed. Sometimes, someone isn't like what you think!
