### ISSUE TITLE
Avatar Change

### ISSUE THREAD

**Issue by YiqinZhao** [c422/c422-src#26]
@Arabaku You are using a cartoon avatar now, however, I would like to recommend a real-world photo as your avatar. Because it is a common choice in the official organization website. How is your opinion?

Of course, you could deny. You have every right to keep your privacy.

**Comment by seiuryuu** [comment]
I have decided to use real-world photo as my avatar since beginning. Yesterday when I coded, though, I found that I had no  real-world photo in my MacBook Pro. Now I am going to change it.

**Comment by seiuryuu** [comment]
Changed.
